version: '3.8'

services:
  web:
    build: .
    container_name: symfony_app
    ports:
      - "8080:80"  # Expose le port 80 du conteneur sur le port 8080 de votre machine
    volumes:
      - .:/var/www/html  # Monte le code source dans le conteneur
    environment:
      - DATABASE_URL=postgresql://avnadmin:AVNS_fDJfCnVhKRHNpeaM66d@pg-39cad0bd-rvalisoa3-28cc.i.aivencloud.com:14567/defaultdb?sslmode=require
      - APP_ENV=prod
      - APP_SECRET=980b726dfaf5489b46c341d937b76e72
